### ISSUE TITLE
Pasta vazia

### ISSUE THREAD

**Issue by LuizSantos1** [contardi/installments#1]
Instalei o módulo no Magento 1.9.0.1
no entanto, quando vou a Sistema/Configuração/Catálogo/Parcelas
ao clicar, aparece um erro 404 dizendo que este campo está vazio.

Já reinstalei e segue o problema.

**Comment by contardi** [comment]
Olá Luiz, bom dia.
O módulo estava bem desatualizado, coloquei uma versão mais atualizada, existem novas correções que ainda não foram testadas, assim que validar subirei aqui também

A pasta de interface estava errada então pode excluir os arquivos e instalar de novo

Verifique se foi corrigido, por favor.

Se ocorrer o erro 403, você precisará sair e entrar de novo na administração para que as permissões sejam atualizadas.

Outra coisa, nessa versão estou usando o jquery-1.12, que é a versão padrão do Magento 1.9.3.x, caso use uma outra versão na sua loja, comente dentro do arquivo de layout (contardi/installments.xml) a parte que chama a jQuery.

**Comment by LuizSantos1** [comment]
Olá, tudo bem?

Olha, teste o código e funciona perfeitamente.

Vi que tens um para "configurable", espero que consiga
colocá-lo para funcionar, pois até hoje, não vi um módulo de parcelamento
que consiga fazer isso :)


Sugestões estéticas:

Sugiro que melhore o layout da tabela de parcelamento (onde mostra as parcelas de 1 a 12)
Ela está um pouco confusa e/ou com excesso de informação.

Por exemplo, há uma neste site que aparece ao clicar em "Simular parcelas" logo abaixo do preço:
https://www.ultraeletronicos.com/novo-beats-solo3-wireless-prata.html

No entanto, estéticamente falando, acho a solução da Balbino mais elegante:
https://www.balbinoshop.com.br/camera-gopro-hero-5-black.html

Ele tem a opção de clicar em "Clique aqui e confira as parcelas em até 12x"
Esse efeito é em jQuery, se não me engano em "accordion".


Enfim, obrigado pelo código, havendo alguma novidade, irei testar com certeza.

**Comment by contardi** [comment]
Olá, bom dia.
Então, eu fiz mais uma correção apenas para exibição do preço à vista

Na verdade, eu não me dediquei muito a esse módulo, fiz para um amigo poder usar na loja dele, então, acabei não fazendo CSS algum, o módulo funciona com produto configurável também, e com produto empacotado, agrupado e virtual, mas depende de classes, se seu layout for muito personalizado, tem que editar o arquivo de JS, installments.js para adequar

Tem também uma classe JS que pode ser usada em todo o cósidog que é "installments", essa classe permite que você use o parcelamento baseado nas configurações do admin.

Depois vou dar uma atenção maior nisso, 

Qualquer coisa, só falar

**Comment by LuizSantos1** [comment]
O meu tema puxa as informações da pasta "base", apesar de muito customizado.
Como faz para fazer a chamada dos produtos configuráveis na view.phtml da página do produto?
Outra pergunta, essa configuração (para produtos configuráveis) é aplicável também para os produtos com opções personalizadas? 

Enfim, havendo novidades, vou testar e te passar o feedback. 
Para não ficar só no "venha a nós", também te dou uma dica de plugin que 
estou testando agora. 

Eu usava o Tagalys para a busca, é ótimo e atende perfeitamente
lojas de pequeno porte com 1000 produtos ou menos (versão gratuita). 
No entanto, descobri sem querer outro que se chama "ExpertRec", se não 
me engano, eles se inspiraram no plugin da "Algolia", e fizeram um trabalho ótimo, 
pois conseguiram ser melhores que a maioria dos plugins que vi no mercado. 
Além de ter autocomplete, ele é tolerante a erros de escrita. 

Vale à pena da uma conferida. 
Um abraço!

**Comment by contardi** [comment]
Faz assim

Coloca dentro da sua view a seguinte chamada

Preço parcelado: <?php echo $this->getChildHtml('preco_parcelado'); ?>
Preço à vista: <?php echo $this->getChildHtml('preco_avista'); ?>

Na view do produto existe também outra opção de exibir todas as parcelas 
<?php echo $this->getChildHtml('installments'); ?>

Eu coloquei o módulo num Magento cru que temos aqui na empresa que eu trabalho pra testar e funcionou perfeitamente

Depois me passe seu e-mail no thiago@contardi.com.br que eu mando o link se você quiser conferir

Atte

**Comment by contardi** [comment]
@LuizSantos1
Deu certo funcionar o parcelamento? Se precisar de ajuda, só falar.

**Comment by LuizSantos1** [comment]
Oi, tudo bem?
Como disse, depois que você atualizou, funcionou direitinho.
A questão agora é o CSS ou deixá-lo mais digamos "elegante"... 

Mas funcionou, sim. Não testei a função configurável, mas foi por falta de tempo mesmo. 

Se houver alguma atualização no CSS ou no visual, me avisa, assim eu posso fazer
testes, OK? Ah sim, havendo planos para a versão Magento 2, também, já que pretendo
migrar este e outro site para esta versão até o final do ano. 

Achei super elegante a solução do Deivinson Arthur para essa loja, mas infelizmente,
ele também não vende o módulo dele... 
https://www.fitmoda.com.br/conjunto-para-academia-azul-em-jacquard-cirre-ref-3-3-2092c-06.html
Repare logo abaixo do "formas de parcelamento"... 

Mudando de assunto, teve a oportunidade de testar o plugin de busca? 
Eu estou impressionado com a capacidade de adaptação dele, mesmo nos melhores
plugins pagos que eu já testei, essa capacidade de corrigir e adivinhar o que o cliente
está procurando, é impressionante!

**Comment by LuizSantos1** [comment]
Ops, quis dizer repare logo abaixo do "Guia de Medidas" em "Formas de Parcelamento"
