### ISSUE TITLE
Uncaught TypeError: jQuery.installments is not a constructor

### ISSUE THREAD

**Issue by LuizSantos1** [contardi/installments#2]
Aparece um erro
"Uncaught TypeError: jQuery.installments is not a constructor" 

Versão Magento: 1.9.4.5 
Versão PHP: 7.3 (estou usando OpenMage que é compatível)

**Comment by LuizSantos1** [comment]
Era um problema de conflito com outro módulo da Facilstore, ignore.

**Comment by LuizSantos1** [comment]
Retificando, consegui fazer o módulo funcionar, pelo menos nos produtos simples. 
O erro "Uncaught TypeError: jQuery.installments is not a constructor" segue lá, mas de momento,
nos produtos simples (que são os que eu estou testando) está funcionando. 

Entendo editar a tabela de parcelas para que fique as linhas no mesmo local.
Quem souber como consertar, agradeço

As linhas ficam assim:
2x de R$485,25
Total R$970,49
1,65% a.m.

E eu gostaria que ficassem assim:
2x de R$485,25 - Total R$970,49 - 1,65% a.m.

Att
Luiz Santos

**Comment by contardi** [comment]
Olá Luiz, só aplicar um CSS, eu vou trocar as divs por span, era div pois um CSS da loja que usou usava o seletor div.'classe'.
Mas se aplicar um CSS ele fica em uma linha só.

Sobre não funcionar em configuráveis, teria mais informações?

Atte

**Comment by LuizSantos1** [comment]
@contardi , tudo bem?

Eu não sou muito com com CSS, consigo fazer mais edições em códigos phtml e php
No entanto, eu usei um código CSS para fazer o **dropdown on hover** no plugin de parcelamento
do Bruno Silva (FacilStore), e funcionou.
https://github.com/brunoosilva/Modulo-Parcelamento-Magento/blob/master/app/design/frontend/base/default/template/facilestore/quota/productquota.phtml

A tabela de parcelamento desse plugin fica alinada corretamente,
como "Nr da Parcela" - "Valor da Parcela" - "Total' - Juros aplicado (ou não)

O problema com esse plugin? O juros não está funcionando, eu tentei pelo admin panel e 
editar diretamente no php e phtml como já fiz em um plugin para Magento 2, mas não funcionou.

O funcionamento do seu é bastante semelhante ao dele, mas com mais funções, como atualização
para produtos configuráveis. No entanto, não consigo fazer com que o css dropdown alinhe a tabela
de parcelamento.

De momento, eu "resolvi" o problema, fazendo uma "gambiarra", adaptando 2 dos 3 códigos de parcelamento
que eu tenho aqui disponível. Fiz isso fazendo um backup do arquivo "productquota.phtml" do plugin
mencionado acima, deletei tudo dentro desse arquivo, e inseri esse código abaixo já com todas as adaptações,
com dropdown on hover e imagens em svg. Acho que ficou legal, mas não é tão prático de editar as taxas
de juros como no seu. 

O ruim, é que se quiser fazer alguma alteração no juros, teria que fazer manualmente.
Mas enfim, este é o link de como ficou no frontend:

E aqui, como ficou o código completo para a página do produto: 

`<div id="parcelado" >
<?php
$_product = $this->getProduct();
$valor = $_product->getFinalPrice();
$_max_parcelas = 12;// Máximo de parcelas no cartão
$cartao =number_format($valor * 1.2049 /$_max_parcelas,2,',','.');
$boleto = $valor * 0.95;//Desconto à vista por Depósito Bancário
echo '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="18" x="0" y="0" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512" xml:space="preserve" class=""><g transform="matrix(0.97,0,0,0.9700000000000001,7.680000000000007,37.679998283386425)"><g xmlns="http://www.w3.org/2000/svg"><g><path d="M0,255.995v192c0,17.664,14.368,32,32,32h448c17.664,0,32-14.336,32-32v-192H0z M448,415.995H64v-64h384V415.995z" fill="#2c85c8" data-original="#000000" style="" class=""/></g></g><g xmlns="http://www.w3.org/2000/svg"><g><path d="M480,127.995H32c-17.632,0-32,14.368-32,32v32h512v-32C512,142.363,497.664,127.995,480,127.995z" fill="#2c85c8" data-original="#000000" style="" class=""/></g></g><g xmlns="http://www.w3.org/2000/svg"><g><path d="M415.2,42.939c-2.752-8.096-11.232-12.64-19.584-10.336L173.728,95.995h259.136L415.2,42.939z" fill="#2c85c8" data-original="#000000" style="" class=""/></g></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g></g></svg>
<font style="font-size:14px; font-weight:default; color:#3781b8;">'.$_max_parcelas.'x</font> <font 
style="color:#808080">de</font> <font style="font-size:14px; font-weight:default; color:#156EAF;">R$ 
'.$cartao.'</font></strong> <font style="color:#808080"> - juros 1,99% a.m
</font> </font><br/><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"width="20" height="18" x="0" y="0" viewBox="0 0 511.626 511.627" style="enable-background:new 0 0 512 512" xml:space="preserve" class=""><g transform="matrix(0.9600000000000001,0,0,0.9600000000000001,10.232520141601583,60.232519836425695)"><g xmlns="http://www.w3.org/2000/svg"><g><rect x="134.761" y="54.816" width="17.699" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="98.786" y="54.816" width="8.848" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="197.568" y="54.816" width="8.852" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="179.581" y="54.816" width="8.852" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="26.84" y="54.816" width="9.136" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="53.959" y="54.816" width="8.851" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect y="54.816" width="17.987" height="401.994" fill="#2c85c8" data-original="#000000" style=""/><rect x="215.557" y="54.816" width="8.852" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="394.856" y="54.816" width="17.986" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="439.966" y="54.816" width="26.837" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="475.653" y="54.816" width="9.134" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="493.64" y="54.816" width="17.986" height="401.994" fill="#2c85c8" data-original="#000000" style=""/><rect x="332.045" y="54.816" width="17.987" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="368.019" y="54.816" width="17.987" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="296.072" y="54.816" width="17.986" height="401.707" fill="#2c85c8" data-original="#000000" style=""/><rect x="251.243" y="54.816" width="17.989" height="401.707" fill="#2c85c8" data-original="#000000" style=""/></g></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g><g xmlns="http://www.w3.org/2000/svg"></g></g></svg>&nbsp;
<font style="font-size:14px; font-weight:bold; 
color:#b73741;">R$'.number_format($boleto,2,',','.').'</font> <font style="color:#808080">à vista - 5% de desconto </font>';
?></font><br>
<style>
.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  width: 260px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}
</style>
<body>
<div class="dropdown">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="18" x="0" y="0" viewBox="0 0 511.979 511.979" style="enable-background:new 0 0 512 512" xml:space="preserve" class=""><g><g xmlns="http://www.w3.org/2000/svg"><path d="m498.819 166.33-153.171-153.171c-17.546-17.546-46.096-17.544-63.64 0l-192.201 192.202h-44.807c-24.813 0-45 20.187-45 45v216.617c0 24.813 20.187 45 45 45h344.62c24.813 0 45-20.187 45-45v-172.81l64.199-64.199c17.546-17.545 17.546-46.093 0-63.639zm-195.597-131.958c2.925-2.924 6.766-4.387 10.607-4.387s7.682 1.463 10.606 4.387l78.925 78.925-92.064 92.064h-179.064zm101.398 432.606c0 8.271-6.729 15-15 15h-344.62c-8.271 0-15-6.729-15-15v-216.617c0-8.271 6.729-15 15-15h344.62c8.271 0 15 6.729 15 15zm-8.896-261.192c-1.998-.272-4.033-.425-6.104-.425h-35.898l70.851-70.852 21.214 21.214zm81.882 2.971-42.986 42.986v-1.382c0-11.402-4.271-21.821-11.286-29.759l43.666-43.666 10.606 10.606c5.849 5.849 5.849 15.366 0 21.215z" fill="#2c85c8" data-original="#000000" style="" class=""/><path d="m60 406.574h55.819v30h-55.819z" fill="#2c85c8" data-original="#000000" style="" class=""/><path d="m146.267 406.574h55.819v30h-55.819z" fill="#2c85c8" data-original="#000000" style="" class=""/><path d="m232.534 406.574h55.82v30h-55.82z" fill="#2c85c8" data-original="#000000" style="" class=""/><path d="m318.801 406.574h55.819v30h-55.819z" fill="#2c85c8" data-original="#000000" style="" class=""/><path d="m161.267 280.766h-101.267v90h101.267zm-30 60h-41.267v-30h41.267z" fill="#2c85c8" data-original="#000000" style="" class=""/></g></g></svg>&nbsp;
  </font> <font style="color:#808080">Ver parcelas </font></button>
  <div class="dropdown-content">
    <a <ul>
                    <left>
<style type="text/css">

</style><table>

<table>
 
  <tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.000001;

    for($i=1; $i < 2; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 2 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;<span style="font-size: small; color: #555555;">R$ '.number_format($parcela ,2,',','.').'&nbsp;
    - sem juros
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>';
        echo($i % 2 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?> 

  </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.01591;

    for($i=2; $i < 3; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 3 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 3 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
  </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0237;

    for($i=3; $i < 4; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 3 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 3 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
  </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.02835;

    for($i=4; $i < 5; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 4 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 4 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
  </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=5; $i < 6; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 5 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 5 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
  </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=6; $i < 7; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 6 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 6 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
 </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=7; $i < 8; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 7 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 7 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
 </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=8; $i < 9; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 8 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 8 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
 </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=9; $i < 10; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 9 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 9 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
 </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=10; $i < 10; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 10 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 10 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
 </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=11; $i < 12; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 11 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 11 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<tr>
 </tr>
<?php
    $_product = $this->getProduct();
    $capital = $_product->getFinalPrice();
    $taxa = 0.0299;

    for($i=12; $i < 13; $i++){
         $parcela = $taxa / (1 - pow((1 + $taxa), ($i * -1))) * $capital;
        echo($i % 11 ? '' : '<tr>');   
        echo '<td><span style="font-size: small; color: #555555;">&nbsp;&nbsp;&nbsp;&nbsp;'.($i).' x &nbsp;&nbsp;R$ '.number_format($parcela ,2,',','.').'&nbsp;- 1,99% a.m
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>';
        echo($i % 11 ? '&nbsp;&nbsp;</tr>' : ''). "\n";
      }
?>
<br>
<tr>
  </tr>&nbsp;&nbsp;
  <img src="https://ultraeletronicos.com/media/wysiwyg/infortis/fortis/slideshow/icone-cartoes-ultra-7.png">
</table>
</left>
                    </ul></a>
  </div>
</div>

</body><br><br>
</div>
`
