### ISSUE TITLE
Parcelamento não aparece na listagem

### ISSUE THREAD

**Issue by rodsonwebdesigner** [contardi/installments#3]
Olá.

Instalei o módulo e configurei na minha loja, porém o preço parcelado não aparece na listagem. Segue página: https://www.mixpelinfo.com.br/informatica/computadores/mixtech/

Na página do produto funcionou muito bem. Inclusive trabalhei no visual e melhorei a tabela de parcelamento, transformando-a em um modal: https://www.mixpelinfo.com.br/produto/computador-mixtech-core-i3-7100-4gb-ssd-120gb-teclado-e-mouse

**Comment by contardi** [comment]
Bom dia Robson, 

Chegou a colocar o trecho nos arquivos de listagem:

```
Preço parcelado: <?php echo $this->getChildHtml('preco_parcelado'); ?>
Preço à vista: <?php echo $this->getChildHtml('preco_avista'); ?>
```

Seria possível enviar os arquivos onde você inseriu essas chamadas?

**Comment by rodsonwebdesigner** [comment]
Olá, bom dia,

Coloquei sim. Estou anexando os arquivos para você dar uma olhadinha.

Obrigado pela atenção e desculpe-me pela demora em responder.
[Documents.zip](https://github.com/contardi/installments/files/6365154/Documents.zip)

**Comment by rodsonwebdesigner** [comment]
Olá, bom dia.

Alguma novidade sobre este problema?

Obrigado.

**Comment by contardi** [comment]
Então, eu olhei o código do list e parece OK
No layout, ele adiciona nas páginas
`

    <catalog_category_default>
        <reference name="product_list">
            <block type="installments/prices" name="preco.a.vista.produto" as="preco_avista" template="contardi/installments/prices/avista.phtml" />
            <block type="installments/prices" name="preco.parcelado.produto" as="preco_parcelado" template="contardi/installments/prices/parcelado.phtml" />
        </reference>
    </catalog_category_default>

    <catalog_category_layered>
        <reference name="product_list">
            <block type="installments/prices" name="preco.a.vista.produto" as="preco_avista" template="contardi/installments/prices/avista.phtml" />
            <block type="installments/prices" name="preco.parcelado.produto" as="preco_parcelado" template="contardi/installments/prices/parcelado.phtml" />
        </reference>
    </catalog_category_layered>

    <catalogsearch_result_index>
        <reference name="search_result_list">
            <block type="installments/prices" name="preco.a.vista.produto" as="preco_avista" template="contardi/installments/prices/avista.phtml" />
            <block type="installments/prices" name="preco.parcelado.produto" as="preco_parcelado" template="contardi/installments/prices/parcelado.phtml" />
        </reference>
    </catalogsearch_result_index>`
    

Se o layout estiver chamando certo, e o list for esse mesmo, deveria chamar, mas tenho que ver
Testei hoje num Magento 1.9.4.5 e deu certo

Não sei o que seria no seu caso

**Comment by rodsonwebdesigner** [comment]
Obrigado pelo retorno meu amigo.

Estranho mesmo, pois era pra estar funcionando.

Estou usando um tema personalizado e consegui fazê-lo funcionar inserindo todo o código do arquivo parcelado.phtml diretamente no arquivo price.html

Minha versão é a 1.9.2.4
